version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: runeterra
    environment:
      POSTGRES_DB: aurelionsol
      POSTGRES_USER: olkaida
      POSTGRES_PASSWORD: estrelas123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: